# Generated by Django 4.1.2 on 2023-03-18 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_materia_cantcreditos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('idCarrera', models.IntegerField(primary_key=True, serialize=False)),
                ('nombreCarrera', models.CharField(max_length=50)),
                ('numSemestresTotales', models.IntegerField()),
                ('numTotalCreditos', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='estudiante',
            name='promedioAcumulado',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
