# Generated by Django 4.0 on 2023-03-18 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_carrera_estudiante_promedioacumulado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrera',
            name='idCarrera',
        ),
        migrations.AddField(
            model_name='carrera',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
